### ISSUE TITLE
Red alert icon displaying when no javascript errors on page

### ISSUE THREAD

**Issue by darrylluther** [barbushin/javascript-errors-notifier#21]
I see that this was fixed in v2.1.10, but I am on v2.1.11 and the issue is present today. 
![image](https://cloud.githubusercontent.com/assets/4376954/8458674/3acda9e8-1fcd-11e5-9fd9-e7d51d84552a.png)
![image](https://cloud.githubusercontent.com/assets/4376954/8458701/690d2acc-1fcd-11e5-8c50-3cca50dd3fed.png)

**Comment by NathanCJohnson** [comment]
I'm having this issue as well.

**Comment by zhgabor** [comment]
no commente, this tool is too handy i like that deveoper has the times to work on this.
when i see the red sign it triggers my urge to check the console for errors, gives me thoose goose bumps, just a reminder to fix this, thanke schon

**Comment by codankserkan** [comment]
i have same issue

**Comment by barbushin** [comment]
Hey guys! Could you please try to uninstall extension, and install `JavaScript Errors Notifier (no FairShare)` version? https://chrome.google.com/webstore/detail/javascript-errors-notifie/fhbooopdkjpkogooopbmabepipljagfn?utm_source=chrome-app-launcher-info-dialog and check if this problem is reproduced?

**Comment by barbushin** [comment]
I deployed fixed `2.1.12` version. It looks like there was a problems with analytics module.

**Comment by darrylluther** [comment]
Thanks for the quick response. Back to working as expected!
