### ISSUE TITLE
Browser support Firefox

### ISSUE THREAD

**Issue by guilhas** [barbushin/javascript-errors-notifier#65]
Hello,

Any idea of supporting Firefox?

Regards,
Lino

**Comment by barbushin** [comment]
Sorry, it's not possible.

**Comment by captainbrosset** [comment]
I tested this in Firefox, which supports a lot of the same APIs that Chrome does, and it worked.

I just had to fix a small thing in the manifest: `"options_page": "options.html"`.
It looks like Firefox does not recognize this configuration at all, and that prevents the addon from loading.

But other than this, it appears to work fine, as shown below on cnn.com:

<img width="719" alt="capture" src="https://user-images.githubusercontent.com/1152698/38236873-c9cdf748-3725-11e8-8898-98c99af0bf13.PNG">

This extension is really useful for people who just want to know if something's wrong quickly without opening devtools first.
It would be really good to make it Firefox-compatible (especially because it looks like it can be done very easily) and have it on addons.mozilla.org for Firefox users to use too.

**Comment by juliandescottes** [comment]
You can specify an options page by using the following syntax:

```
"options_ui": {
  "page": "options.html",
  "browser_style": true
},
```

It is supported by both Chrome and Firefox :
- https://developer.mozilla.org/en-US/Add-ons/WebExtensions/user_interface/Options_pages
- https://developer.chrome.com/extensions/optionsV2

**Comment by MikeRatcliffe** [comment]
@barbushin It really would be awesome if you could make the small change and make it available in both the Firefox and Chrome stores!

**Comment by barbushin** [comment]
Here we go https://addons.mozilla.org/en-US/firefox/addon/javascript-errors/

**Comment by barbushin** [comment]
Guys, please rate it in FF store. Thanks!
