### ISSUE TITLE
Uncaught TypeError: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by nikolaybobrovskiy** [barbushin/javascript-errors-notifier#78]
Hello!
Please look at this screenshot: https://s3.amazonaws.com/donnicky_screenshots/2018-02-01_03-43-22_d177c59a-70c8-468c-af04-bfbff6788cec.png
If reject bluebird's promise with Error then exception occurs in add-on code:
```
VM896:24 Uncaught TypeError: Cannot read property 'message' of undefined
    at <anonymous>:24:31
    at bluebird.js:817
    at activeFireEvent (bluebird.js:879)
    at fireRejectionEvent (bluebird.js:1222)
    at Promise._notifyUnhandledRejection (bluebird.js:728)
    at bluebird.js:154
```

**Comment by danielkalen** [comment]
What I found out about this error:
It occurs at the [unhandledRejection handler](https://github.com/barbushin/javascript-errors-notifier/blob/3361df20c5da64f5dc949d0c32634548503dee67/content.js#L122) when the code attempts to access the error object's `reason` property which is undefined in the case of bluebird errors because bluebird [assigns the promise error object](http://bluebirdjs.com/docs/api/error-management-configuration.html) to `err.detail` and not `err.reason`. Can't find a workaround this without modifing bluebird or this extension.
